spin_manifest_version = 2

[application]
name = "product-api"
version = "0.1.0"
authors = ["thangchung <thangchung@nomail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "product-api"

[component.product-api]
source = "service.wasm"
allowed_outbound_hosts = []
[component.product-api.build]
command = "./build.sh"
